### ISSUE TITLE
Add topic: scopus

### ISSUE THREAD

**Issue by katrinleinweber** [geekabhi007/ElsevierScopus-CitationSearch-Implementation#3]
I think this would be better findable, if displayed on [GitHub.com/topics/scopus](https://github.com/topics/scopus), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by abhi1d** [comment]
Thanks for reminding me.
Now I added the topics. Now you can search in github.com/topics/scopus.

**Comment by katrinleinweber** [comment]
Cool, thanks :-)
